# Generated by Django 6.0.7 on 2026-08-02 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisors', '0001_initial'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advisor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='advisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advisoravailability',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='availabilities', to='advisors.advisor'),
        ),
        migrations.AddField(
            model_name='advisoravailability',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='companies.company'),
        ),
        migrations.AddField(
            model_name='advisoravailability',
            name='configured_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configured_availabilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advisorsupervision',
            name='advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisions', to='advisors.advisor'),
        ),
        migrations.AddField(
            model_name='advisorsupervision',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_supervisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advisorsupervision',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='companies.company'),
        ),
        migrations.AddField(
            model_name='advisorsupervision',
            name='supervisor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervised_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='advisor',
            index=models.Index(fields=['company', 'is_active', 'is_available'], name='advisors_ad_company_114136_idx'),
        ),
        migrations.AddConstraint(
            model_name='advisor',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_advisor_code_per_company'),
        ),
        migrations.AddConstraint(
            model_name='advisor',
            constraint=models.CheckConstraint(condition=models.Q(('default_event_duration_minutes__gt', 0)), name='advisor_duration_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='advisor',
            constraint=models.CheckConstraint(condition=models.Q(('max_daily_events__isnull', True), ('max_daily_events__gt', 0), _connector='OR'), name='advisor_daily_limit_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='advisoravailability',
            constraint=models.UniqueConstraint(fields=('advisor', 'day_of_week', 'start_time', 'end_time'), name='unique_availability_block'),
        ),
        migrations.AddConstraint(
            model_name='advisoravailability',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_week__gte', 0), ('day_of_week__lte', 6)), name='availability_valid_day'),
        ),
        migrations.AddConstraint(
            model_name='advisoravailability',
            constraint=models.CheckConstraint(condition=models.Q(('slot_duration_minutes__gt', 0)), name='availability_slot_gt_zero'),
        ),
        migrations.AddIndex(
            model_name='advisorsupervision',
            index=models.Index(fields=['company', 'supervisor_user', 'is_active'], name='advisors_ad_company_91614d_idx'),
        ),
        migrations.AddConstraint(
            model_name='advisorsupervision',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'advisor'), name='one_active_supervision_per_advisor'),
        ),
    ]
