# Generated by Django 6.0.7 on 2026-08-23 01:10

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSequence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='inbox_sequence', serialize=False, to='companies.company')),
                ('last_display_id', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=150)),
                ('country', models.CharField(default='Colombia', max_length=64)),
                ('avatar_initial', models.CharField(blank=True, max_length=2)),
                ('avatar_color', models.CharField(blank=True, max_length=7)),
                ('chatbot_enabled', models.BooleanField(default=True)),
                ('nickname', models.CharField(blank=True, max_length=128)),
                ('owner', models.CharField(blank=True, default='—', max_length=128)),
                ('source', models.CharField(blank=True, default='Inbound message', max_length=128)),
                ('source_id', models.CharField(blank=True, max_length=128)),
                ('source_url', models.CharField(blank=True, max_length=512)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_contacts', to='clients.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_id', models.PositiveIntegerField(blank=True, null=True)),
                ('inbox', models.CharField(default='Inmobiliar-ia', max_length=128)),
                ('channel', models.CharField(default='whatsapp', max_length=32)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('pending', 'Pending')], default='open', max_length=20)),
                ('assignment', models.CharField(choices=[('unassigned', 'Unassigned'), ('me', 'Agent'), ('bot', 'Bot')], default='unassigned', max_length=16)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('last_message_preview', models.CharField(blank=True, max_length=255)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='companies.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='inbox.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('message_type', models.SmallIntegerField(choices=[(0, 'Inbound'), (1, 'Outbound')])),
                ('sender_type', models.CharField(choices=[('contact', 'Contact'), ('bot', 'Bot'), ('agent', 'Agent')], default='contact', max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('received', 'Received')], default='sent', max_length=20)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('system', 'System')], default='text', max_length=16)),
                ('wa_message_id', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbox_messages', to='companies.company')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='inbox.contact')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='inbox.conversation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppChannel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inbox_name', models.CharField(default='Inmobiliar-ia', max_length=128)),
                ('ycloud_api_key', models.CharField(blank=True, max_length=255)),
                ('ycloud_from', models.CharField(blank=True, max_length=20)),
                ('ycloud_api_base', models.CharField(blank=True, max_length=255)),
                ('n8n_webhook_url', models.URLField(blank=True, max_length=512)),
                ('n8n_timeout_seconds', models.FloatField(default=5.0)),
                ('verify_token', models.CharField(blank=True, max_length=128)),
                ('webhook_key_prefix', models.CharField(blank=True, max_length=16)),
                ('webhook_key_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='whatsapp_channel', to='companies.company')),
            ],
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company', 'phone_number'], name='inbox_conta_company_1888d4_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company', 'last_contact_at'], name='inbox_conta_company_0d0256_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('company', 'phone_number'), name='unique_inbox_contact_phone_per_company'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['company', '-last_activity_at'], name='inbox_conve_company_02c06c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['company', 'assignment'], name='inbox_conve_company_00bbb2_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['contact', 'status'], name='inbox_conve_contact_872733_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('company', 'display_id'), name='unique_inbox_display_id_per_company'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-id'], name='idx_inbox_conv_id_desc'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='idx_inbox_conv_created'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['contact', 'created_at'], name='idx_inbox_contact_created'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_type', 'created_at'], name='idx_inbox_sender_created'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('wa_message_id__isnull', False)), fields=('company', 'wa_message_id'), name='unique_inbox_wa_message_id_per_company'),
        ),
        migrations.AddConstraint(
            model_name='whatsappchannel',
            constraint=models.UniqueConstraint(condition=models.Q(('webhook_key_hash', ''), _negated=True), fields=('webhook_key_hash',), name='unique_inbox_webhook_key_hash'),
        ),
    ]
