# Generated by Django 6.0.7 on 2026-08-31 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0002_initial'),
        ('companies', '0001_initial'),
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='advisors.advisor'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['company', 'advisor', '-last_activity_at'], name='inbox_conve_company_3d66e8_idx'),
        ),
    ]
