# Generated by Django 6.0.7 on 2026-08-02 03:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisors', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('CONFIRMED', 'Confirmed'), ('STARTED', 'Started'), ('COMPLETED', 'Completed'), ('UPDATED', 'Updated'), ('CANCELLED', 'Cancelled'), ('RESCHEDULED', 'Rescheduled'), ('REASSIGNED', 'Reassigned'), ('NO_SHOW', 'No show'), ('REMINDER_SENT', 'Reminder sent')], max_length=16)),
                ('previous_status', models.CharField(blank=True, max_length=16)),
                ('new_status', models.CharField(blank=True, max_length=16)),
                ('previous_data', models.JSONField(blank=True, default=dict)),
                ('new_data', models.JSONField(blank=True, default=dict)),
                ('actor_type', models.CharField(default='USER', max_length=16)),
                ('source', models.CharField(blank=True, max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulingConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default', max_length=100)),
                ('default_event_duration_minutes', models.PositiveIntegerField(default=60)),
                ('minimum_advance_minutes', models.PositiveIntegerField(default=0)),
                ('maximum_advance_days', models.PositiveIntegerField(default=90)),
                ('default_buffer_before_minutes', models.PositiveIntegerField(default=0)),
                ('default_buffer_after_minutes', models.PositiveIntegerField(default=0)),
                ('assignment_strategy', models.CharField(choices=[('FIRST_AVAILABLE', 'First available'), ('LEAST_EVENTS', 'Least events'), ('ROUND_ROBIN', 'Round robin'), ('PRIORITY', 'Priority'), ('RANDOM', 'Random')], default='FIRST_AVAILABLE', max_length=20)),
                ('allow_same_day_booking', models.BooleanField(default=True)),
                ('require_advisor_confirmation', models.BooleanField(default=False)),
                ('allow_automatic_reassignment', models.BooleanField(default=False)),
                ('allow_events_outside_availability', models.BooleanField(default=False)),
                ('allow_advisor_create_events', models.BooleanField(default=True)),
                ('allow_advisor_edit_availability', models.BooleanField(default=True)),
                ('allow_supervisor_create_events', models.BooleanField(default=True)),
                ('allow_supervisor_reassign_events', models.BooleanField(default=True)),
                ('allow_supervisor_edit_availability', models.BooleanField(default=True)),
                ('reminder_minutes_before', models.PositiveIntegerField(default=60)),
                ('timezone', models.CharField(default='America/Bogota', max_length=64)),
                ('is_default', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdvisorAssignmentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('advisor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_state', to='advisors.advisor')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('PROPERTY_VISIT', 'Property visit'), ('CLIENT_MEETING', 'Client meeting'), ('PHONE_CALL', 'Phone call'), ('INTERNAL_MEETING', 'Internal meeting'), ('PERSONAL_BLOCK', 'Personal block'), ('LUNCH', 'Lunch'), ('VACATION', 'Vacation'), ('OTHER', 'Other')], default='PROPERTY_VISIT', max_length=24)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show'), ('RESCHEDULED', 'Rescheduled')], default='PENDING', max_length=16)),
                ('source', models.CharField(choices=[('CHATBOT', 'Chatbot'), ('MANUAL', 'Manual'), ('SYSTEM', 'System'), ('API', 'API'), ('CALENDAR_SYNC', 'Calendar sync')], default='MANUAL', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('timezone', models.CharField(default='America/Bogota', max_length=64)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('meeting_url', models.URLField(blank=True)),
                ('property_external_id', models.CharField(blank=True, max_length=128)),
                ('property_code', models.CharField(blank=True, max_length=128)),
                ('property_title', models.CharField(blank=True, max_length=255)),
                ('property_address', models.CharField(blank=True, max_length=255)),
                ('property_url', models.URLField(blank=True)),
                ('chatbot_conversation_id', models.CharField(blank=True, max_length=128)),
                ('chatbot_message_id', models.CharField(blank=True, max_length=128)),
                ('external_reference', models.CharField(blank=True, max_length=128)),
                ('idempotency_key', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_automatically', models.BooleanField(default=False)),
                ('requires_confirmation', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancellation_source', models.CharField(blank=True, max_length=16)),
                ('no_show_type', models.CharField(blank=True, choices=[('CLIENT_NO_SHOW', 'Client'), ('ADVISOR_NO_SHOW', 'Advisor'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('no_show_notes', models.TextField(blank=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='advisors.advisor')),
            ],
        ),
    ]
