# Generated by Django 6.0.7 on 2026-08-02 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='clients.client'),
        ),
        migrations.AddField(
            model_name='event',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='companies.company'),
        ),
        migrations.AddField(
            model_name='event',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rescheduled_children', to='scheduling.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='rescheduled_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rescheduled_parent', to='scheduling.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='started_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventhistory',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventhistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_histories', to='companies.company'),
        ),
        migrations.AddField(
            model_name='eventhistory',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='scheduling.event'),
        ),
        migrations.AddField(
            model_name='schedulingconfiguration',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='companies.company'),
        ),
        migrations.AddField(
            model_name='schedulingconfiguration',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_scheduling_configurations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedulingconfiguration',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_scheduling_configurations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['company', 'advisor', 'start_at'], name='scheduling__company_318da5_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['company', 'status', 'start_at'], name='scheduling__company_832ce1_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='event_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('company', 'idempotency_key'), name='unique_event_idempotency_per_company'),
        ),
        migrations.AddIndex(
            model_name='eventhistory',
            index=models.Index(fields=['company', 'event', 'created_at'], name='scheduling__company_dec464_idx'),
        ),
        migrations.AddConstraint(
            model_name='schedulingconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_default', True)), fields=('company',), name='one_active_default_config_per_company'),
        ),
        migrations.AddConstraint(
            model_name='schedulingconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('default_event_duration_minutes__gt', 0)), name='config_duration_gt_zero'),
        ),
    ]
