# Generated by Django 6.0.7 on 2026-08-31 22:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0002_initial'),
        ('clients', '0002_followup'),
        ('companies', '0001_initial'),
        ('scheduling', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulingconfiguration',
            name='follow_up_after_cancelled_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='schedulingconfiguration',
            name='follow_up_after_completed_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='schedulingconfiguration',
            name='follow_up_after_no_show_days',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='schedulingconfiguration',
            name='follow_up_cooldown_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='schedulingconfiguration',
            name='follow_up_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='schedulingconfiguration',
            name='follow_up_inactive_days',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='schedulingconfiguration',
            name='follow_up_template',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='schedulingconfiguration',
            name='follow_up_template_language',
            field=models.CharField(default='es', max_length=12),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['company', 'client', 'start_at'], name='scheduling__company_499368_idx'),
        ),
    ]
