# Generated by Django 6.0.7 on 2026-08-02 03:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=32)),
                ('normalized_phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('document_type', models.CharField(blank=True, max_length=30)),
                ('document_number', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(choices=[('CHATBOT', 'Chatbot'), ('MANUAL', 'Manual'), ('WEBSITE', 'Website'), ('PHONE_CALL', 'Phone call'), ('OTHER', 'Other')], default='MANUAL', max_length=16)),
                ('preferred_contact_channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('PHONE', 'Phone'), ('EMAIL', 'Email')], default='WHATSAPP', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='companies.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'normalized_phone'], name='clients_cli_company_309fff_idx'), models.Index(fields=['company', 'last_name'], name='clients_cli_company_c1083b_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'normalized_phone'), name='unique_client_phone_per_company')],
            },
        ),
    ]
