# Generated by Django 6.0.7 on 2026-08-31 22:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0002_initial'),
        ('clients', '0001_initial'),
        ('companies', '0001_initial'),
        ('inbox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('normalized_phone', models.CharField(max_length=32)),
                ('reason', models.CharField(choices=[('CANCELLED', 'Cita cancelada'), ('NO_SHOW', 'El cliente no asistió'), ('COMPLETED', 'Visita sin cierre'), ('INACTIVE', 'Sin citas')], max_length=20)),
                ('status', models.CharField(choices=[('SENT', 'Mensaje enviado'), ('DONE', 'Gestionado'), ('DISMISSED', 'Descartado'), ('SNOOZED', 'Pospuesto')], max_length=12)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('message_status', models.CharField(blank=True, max_length=64)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='advisors.advisor')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='clients.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)ss', to='companies.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='inbox.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_follow_ups', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_follow_ups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'advisor', 'due_at'], name='clients_fol_company_b8aee5_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'normalized_phone'), name='unique_follow_up_per_lead')],
            },
        ),
    ]
